# Minimal Makefile for QSPI programmer
# Links only libDaisy (no DaisySP), uses -Os for smallest code size

TARGET ?= patch_sm
LIBDAISY_DIR ?= /opt/daisy/libDaisy

OPT = -Os

CPP_SOURCES ?= qspi_programmer.cpp

PREFIX = arm-none-eabi-
CXX = $(PREFIX)g++
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size

CPU = -mcpu=cortex-m7
FPU = -mfpu=fpv5-d16
FLOAT-ABI = -mfloat-abi=hard
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

LDSCRIPT = $(LIBDAISY_DIR)/core/STM32H750IB_flash.lds

C_INCLUDES = \
  -I. \
  -I$(LIBDAISY_DIR)/src \
  -I$(LIBDAISY_DIR)/src/sys \
  -I$(LIBDAISY_DIR)/src/usbd \
  -I$(LIBDAISY_DIR)/src/usbh \
  -I$(LIBDAISY_DIR)/Drivers/CMSIS_5/CMSIS/Core/Include \
  -I$(LIBDAISY_DIR)/Drivers/CMSIS-Device/ST/STM32H7xx/Include \
  -I$(LIBDAISY_DIR)/Drivers/STM32H7xx_HAL_Driver/Inc \
  -I$(LIBDAISY_DIR)/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy \
  -I$(LIBDAISY_DIR)/core

LIBDIR = -L$(LIBDAISY_DIR)/build

CXXFLAGS = $(MCU) $(OPT) -Wall -fdata-sections -ffunction-sections -fno-exceptions -fno-rtti
CXXFLAGS += $(C_INCLUDES)
CXXFLAGS += -DCORE_CM7 -DSTM32H750xx -DSTM32H750IB -DARM_MATH_CM7 -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER
CXXFLAGS += -DHSE_VALUE=16000000 -DDATA_IN_D2_SRAM
CXXFLAGS += -std=gnu++14 -Wno-register

ASFLAGS = $(MCU) -Wall -fdata-sections -ffunction-sections

LDFLAGS = $(MCU) -specs=nano.specs -specs=nosys.specs
LDFLAGS += -T$(LDSCRIPT)
LDFLAGS += $(LIBDIR)
LDFLAGS += -ldaisy -lc -lm -lnosys
LDFLAGS += -Wl,--gc-sections
LDFLAGS += -Wl,-Map=build/$(TARGET).map,--cref

BUILD_DIR = build

OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
OBJECTS += $(BUILD_DIR)/startup_stm32h750xx.o

all: $(BUILD_DIR)/$(TARGET).bin

$(BUILD_DIR)/%.o: %.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(BUILD_DIR)/startup_stm32h750xx.o: $(LIBDAISY_DIR)/core/startup_stm32h750xx.s | $(BUILD_DIR)
	$(AS) $(ASFLAGS) -c $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS)
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/$(TARGET).bin: $(BUILD_DIR)/$(TARGET).elf
	$(CP) -O binary -S $< $@

$(BUILD_DIR):
	mkdir -p $@

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all clean
